program GCSD;







uses
  Forms,
  UfrmMain in 'UfrmMain.pas' {frmMain},
  UfrmTransferSecretary in 'UfrmTransferSecretary.pas' {frmTransferSecretary},
  UfrmEQOrders in 'UfrmEQOrders.pas' {frmEQOrders},
  UdtmMain in 'UdtmMain.pas' {dtmMain: TDataModule},
  UfrmEQBatchList in 'UfrmEQBatchList.pas' {frmEQBatchList},
  UfrmUTAdmin in 'UfrmUTAdmin.pas' {frmUTAdmin},
  UfrmUTDealCreate in 'UfrmUTDealCreate.pas' {frmUTDealCreate},
  UfrmSettlement in 'UfrmSettlement.pas' {frmSettlement},
  UfrmEQCounters in 'UfrmEQCounters.pas' {frmEQCounters},
  UfrmEQPortfolio in 'UfrmEQPortfolio.pas' {frmEQPortfolio},
  UfrmTransactionSetup in 'UfrmTransactionSetup.pas' {frmTransactionSetup},
  UfrmSetup in 'UfrmSetup.pas' {frmSetup},
  UfrmLogin in 'UfrmLogin.pas' {frmLogin},
  UfrmChangePassword in 'UfrmChangePassword.pas' {frmChangePassword},
  UfrmAccountDetails in 'UfrmAccountDetails.pas' {frmAccountDetails},
  UfrmMMDealList in 'UfrmMMDealList.pas' {frmMMDealList},
  UfrmUTTransaction in 'UfrmUTTransaction.pas' {frmUTTransaction},
  UfrmEQBatchCreate in 'UfrmEQBatchCreate.pas' {frmEQBatchCreate},
  UfrmEQOrderCreate in 'UfrmEQOrderCreate.pas' {frmEQOrderCreate},
  UfrmSelectModule in 'UfrmSelectModule.pas' {frmSelectModule},
  UfrmEQTransactionList in 'UfrmEQTransactionList.pas' {frmEQTransactionList},
  UfrmEQScripSplit in 'UfrmEQScripSplit.pas' {frmEQScripSplit},
  UfrmUTPricing in 'UfrmUTPricing.pas' {frmUTPricing},
  UfrmEQReports in 'UfrmEQReports.pas' {frmEQReports},
  UfrmEQSplitsConsolidations in 'UfrmEQSplitsConsolidations.pas' {frmEQSplitsConsolidations},
  UfrmEQSwapsConversions in 'UfrmEQSwapsConversions.pas' {frmEQSwapsConversions},
  UfrmEQScripRegistration in 'UfrmEQScripRegistration.pas' {frmEQScripRegistration},
  UfrmEQScripSearch in 'UfrmEQScripSearch.pas' {frmEQScripSearch},
  UfrmUTClientReinvest in 'UfrmUTClientReinvest.pas' {frmUTClientReinvest},
  UfrmUTDistributions in 'UfrmUTDistributions.pas' {frmUTDistributions},
  UfrmEQDividends in 'UfrmEQDividends.pas' {frmEQDividends},
  UfrmEQDividendAllocate in 'UfrmEQDividendAllocate.pas' {frmEQDividendAllocate},
  UfrmMMBulkDealAllocation in 'UfrmMMBulkDealAllocation.pas' {frmMMBulkDealAllocation},
  UfrmEndOfMonth in 'UfrmEndOfMonth.pas' {frmEndOfMonth},
  UfrmEQScripRegistrationScrip in 'UfrmEQScripRegistrationScrip.pas' {frmEQScripRegistrationScrip},
  UfrmMMTransaction in 'UfrmMMTransaction.pas' {frmMMTransaction},
  UfrmUTDeals in 'UfrmUTDeals.pas' {frmUTDeals},
  UfrmMMTransactionList in 'UfrmMMTransactionList.pas' {frmMMTransactionList},
  UfrmEQDividendAllocConfirm in 'UfrmEQDividendAllocConfirm.pas' {frmEQDividendAllocConfirm},
  UfrmEQTakeOn in 'UfrmEQTakeOn.pas' {frmEQTakeOn},
  UfrmSplash in 'UfrmSplash.pas' {frmSplash},
  UfrmCalendar in 'UfrmCalendar.pas' {frmCalendar},
  UfrmEQScripSplitCreate in 'UfrmEQScripSplitCreate.pas' {frmEQScripSplitCreate},
  UfrmEQAnalysis in 'UfrmEQAnalysis.pas' {frmEQAnalysis},
  UfrmUTTransferCreate in 'UfrmUTTransferCreate.pas' {frmUTTransferCreate},
  UfrmUTTransfers in 'UfrmUTTransfers.pas' {frmUTTransfers},
  UfrmEQInternalOrders in 'UfrmEQInternalOrders.pas' {frmEQInternalOrders},
  UfrmQuickReports in 'UfrmQuickReports.pas' {frmQuickReports},
  UfrmEQInternalOrderCreate in 'UfrmEQInternalOrderCreate.pas' {frmEQInternalOrderCreate},
  UfrmJournal in 'UfrmJournal.pas' {frmJournal},
  UfrmEQTransactionHistory in 'UfrmEQTransactionHistory.pas' {frmEQTransactionHistory},
  ufrmEmailStatement in 'ufrmEmailStatement.pas' {frmEmailStatement},
  UfrmEQShareTransfer in 'UfrmEQShareTransfer.pas' {frmEQShareTransfer},
  UfrmUTReports in 'UfrmUTReports.pas' {frmUTReports},
  UPRJournal in 'UPRJournal.pas' {frmPRJournal},
  UfrmMMOrder in 'UfrmMMOrder.pas' {frmMMOrder},
  UfrmMMDealAuditTrailList in 'UfrmMMDealAuditTrailList.pas' {frmMMDealAuditTrailList},
  UfrmMMQuickReports in 'UfrmMMQuickReports.pas' {frmMMQuickReports},
  UfrmMMEndOfDay in 'UfrmMMEndOfDay.pas' {frmMMEndOfDay},
  UfrmAgent in 'UfrmAgent.pas' {frmAgent},
  UfrmAgentRate in 'UfrmAgentRate.pas' {frmAgentRate},
  UDateParams in 'UDateParams.pas' {frmDateParam},
  UReportDate in 'UReportDate.pas' {frmReportDate},
  UfrmTransactionSchedule in 'UfrmTransactionSchedule.pas' {frmTransactionSchedule},
  UfrmMMCounterpartyRates in 'UfrmMMCounterpartyRates.pas' {frmMMCounterpartyRates},
  UfrmDashboard in 'UfrmDashboard.pas' {frmDashBoard},
  UfrmEmailer in 'UfrmEmailer.pas' {frmEmailer},
  UfrmMMDealNotes in 'UfrmMMDealNotes.pas' {frmMMDealNoteList},
  UfrmMMDealTermination in 'UfrmMMDealTermination.pas' {frmMMDealTermination},
  UfrmMMDealSettlement in 'UfrmMMDealSettlement.pas' {frmMMDealSettlement},
  UfrmMMOrderRejection in 'UfrmMMOrderRejection.pas' {frmMMOrderRejection},
  UfrmMMOrderConfirmation in 'UfrmMMOrderConfirmation.pas' {frmMMOrderConfirmation},
  UfrmMMOrderList in 'UfrmMMOrderList.pas' {frmMMOrderList},
  UfrmMMSetup in 'UfrmMMSetup.pas' {frmMMSetup},
  UdtmMMHelper in 'UdtmMMHelper.pas' {dtmMMHelper: TDataModule},
  UfrmMMDealAllocate in 'UfrmMMDealAllocate.pas' {frmMMDealAllocate},
  UfrmMMBondAllocationOrderItem in 'UfrmMMBondAllocationOrderItem.pas' {frmMMBondAllocationOrderItem},
  UfrmMMAllocationOrderList in 'UfrmMMAllocationOrderList.pas' {frmMMAllocationOrderList},
  UfrmEQInternalOrder in 'UfrmEQInternalOrder.pas' {frmEQInternalOrder},
  UfrmMMAllocationOrderPlacement in 'UfrmMMAllocationOrderPlacement.pas' {frmMMAllocationOrderPlacement},
  UfrmMMRunningDealList in 'UfrmMMRunningDealList.pas' {frmMMRunningDealList},
  UfrmMMSecurityList in 'UfrmMMSecurityList.pas' {frmMMSecurityList},
  UfrmMMSecurity in 'UfrmMMSecurity.pas' {frmMMSecurity},
  UfrmMMMaturityList in 'UfrmMMMaturityList.pas' {frmMMMaturityList},
  UfrmMMPortfolio in 'UfrmMMPortfolio.pas' {frmMMPortfolio},
  UfrmAccountSearch in 'UfrmAccountSearch.pas' {frmAccountSearch},
  UfrmMMEndOfMonth in 'UfrmMMEndOfMonth.pas' {frmMMEndOfMonth},
  UfrmMMInterestRates in 'UfrmMMInterestRates.pas' {frmMMInterestRates},
  UfrmMMSplash in 'UfrmMMSplash.pas' {frmMMSplash},
  UfrmMMBondAllocationOrder in 'UfrmMMBondAllocationOrder.pas' {frmMMBondAllocationOrder},
  UfrmAccount in 'UfrmAccount.pas' {frmAccount},
  UfrmUTFundSetup in 'UfrmUTFundSetup.pas' {frmUTFundSetup},
  UfrmUTQuickReports in 'UfrmUTQuickReports.pas' {frmUTQuickReports},
  UfrmUTTradingDiary in 'UfrmUTTradingDiary.pas' {frmUTTradingDiary},
  UfrmUTTradingDiaryCreate in 'UfrmUTTradingDiaryCreate.pas' {frmUTTradingDiaryCreate},
  UfrmUTStopOrders in 'UfrmUTStopOrders.pas' {frmUTStopOrders},
  UfrmUTStopOrderDetailsCreate in 'UfrmUTStopOrderDetailsCreate.pas' {frmUTStopOrderDetailsCreate},
  UfrmClient in 'UfrmClient.pas' {frmClient},
  UfrmClientList in 'UfrmClientList.pas' {frmClientList},
  UfrmCounterpartySearch in 'UfrmCounterpartySearch.pas' {frmCounterpartySearch},
  UfrmContact in 'UfrmContact.pas' {frmContact},
  UfrmSignatory in 'UfrmSignatory.pas' {frmSignatory},
  UfrmCompany in 'UfrmCompany.pas' {frmCompany},
  UfrmBranch in 'UfrmBranch.pas' {frmBranch},
  UfrmBankAccount in 'UfrmBankAccount.pas' {frmBankAccount},
  UfrmSystemAccount in 'UfrmSystemAccount.pas' {frmSystemAccount},
  UfrmUser in 'UfrmUser.pas' {frmUser},
  UfrmUserList in 'UfrmUserList.pas' {frmUserList},
  UfrmUserGroup in 'UfrmUserGroup.pas' {frmUserGroup},
  UfrmUserGroupList in 'UfrmUserGroupList.pas' {frmUserGroupList},
  UfrmEQInternalOrderItem in 'UfrmEQInternalOrderItem.pas' {frmEQInternalOrderItem},
  UfrmCounterparty in 'UfrmCounterparty.pas' {frmCounterparty},
  UfrmEQTransaction in 'UfrmEQTransaction.pas' {frmEQTransaction},
  UfrmStockBroker in 'UfrmStockBroker.pas' {frmStockBroker},
  UfrmMMAllocationOrderItem in 'UfrmMMAllocationOrderItem.pas' {frmMMAllocationOrderItem},
  UfrmLock in 'UfrmLock.pas' {frmLock},
  UfrmQuery in 'UfrmQuery.pas' {frmQuery},
  UfrmAccountDetail in 'UfrmAccountDetail.pas' {frmAccountDetail},
  UfrmMMAllocationOrder in 'UfrmMMAllocationOrder.pas' {frmMMAllocationOrder},
  UfrmUTExternal in 'UfrmUTExternal.pas' {frmUTExternal},
  UfrmSigScan in 'UfrmSigScan.pas' {frmSigScan},
  UfrmCurrency in 'UfrmCurrency.pas' {frmCurrency},
  UfrmRejectionReason in 'UfrmRejectionReason.pas' {frmRejectionReason},
  UPRPropertySearch in 'UPRPropertySearch.pas' {frmPRPropertySearch},
  UPRTenantSearch in 'UPRTenantSearch.pas' {frmPRTenantSearch},
  UPRTransaction in 'UPRTransaction.pas' {frmPRTransaction},
  UPRTransactionList in 'UPRTransactionList.pas' {frmPRTransactionList},
  UPRTrustAccountTransaction in 'UPRTrustAccountTransaction.pas' {frmPRTrustAccountTransaction},
  UfrmUTGratuityEmployer in 'UfrmUTGratuityEmployer.pas' {frmUTGratuityEmployer},
  UfrmJointAccount in 'UfrmJointAccount.pas' {frmJointAccount},
  UfrmUTBankActivities in 'UfrmUTBankActivities.pas' {frmUTBankActivities},
  UfrmUTStopOrderDDACC in 'UfrmUTStopOrderDDACC.pas' {frmUTStopOrderDDACC},
  UfrmBarcEPayment in 'UfrmBarcEPayment.pas' {frmBarcEPayment},
  UfrmEQRightsIssue in 'UfrmEQRightsIssue.pas' {frmEQRightsIssue},
  UfrmEQRightsIssueAllocation in 'UfrmEQRightsIssueAllocation.pas' {frmEQRightsIssueAllocation},
  UfrmEQRightsIssueCreate in 'UfrmEQRightsIssueCreate.pas' {frmEQRightsIssueCreate},
  UfrmEQRightsIssueSettle in 'UfrmEQRightsIssueSettle.pas' {frmEQRightsIssueSettle},
  UPRExpenseListing in 'UPRExpenseListing.pas' {frmPRExpenseListing},
  UPRProcessRentals in 'UPRProcessRentals.pas' {frmPRProcessRentals},
  UPRPropertyDeals in 'UPRPropertyDeals.pas' {frmPRPropertyDealList},
  UfrmUTTransactionList in 'UfrmUTTransactionList.pas' {frmUTTransactionList},
  UfrmAgentRateList in 'UfrmAgentRateList.pas' {frmAgentRateList},
  UfrmDiary in 'UfrmDiary.pas' {frmDiary},
  UfrmEQScrip in 'UfrmEQScrip.pas' {frmEQScrip},
  UfrmEQScripManualDischarge in 'UfrmEQScripManualDischarge.pas' {frmEQScripManualDischarge},
  UfrmEQBatchScrip in 'UfrmEQBatchScrip.pas' {frmEQBatchScrip},
  UAuditTrail in 'UAuditTrail.pas' {frmAuditTrail},
  UfrmEQOrderItemConfirm in 'UfrmEQOrderItemConfirm.pas' {frmEQOrderItemConfirm},
  UPRPortfolio in 'UPRPortfolio.pas' {frmPRPortfolio},
  UfrmAccountList in 'UfrmAccountList.pas' {frmAccountList},
  UPRPropertyPurchaseDealList in 'UPRPropertyPurchaseDealList.pas' {frmPRPropertyPurchaseDealList},
  UPRUnitIssueList in 'UPRUnitIssueList.pas' {frmPRUnitIssueList},
  UPRLeaseRentCreate in 'UPRLeaseRentCreate.pas' {frmPRLeaseRentCreate},
  UPRUnitPrice in 'UPRUnitPrice.pas' {frmPRUnitPrice},
  UPRIncomeDistributionList in 'UPRIncomeDistributionList.pas' {frmPRIncomeDistributionList},
  UPRIncomeDistributionCreate in 'UPRIncomeDistributionCreate.pas' {frmPRIncomeDistributionCreate},
  UfrmMMJournal in 'UfrmMMJournal.pas' {frmMMJournal},
  UPRConveyors in 'UPRConveyors.pas' {frmPRConveyors},
  UPRPropertyManager in 'UPRPropertyManager.pas' {frmPRPropertyManager},
  UPREvaluators in 'UPREvaluators.pas' {frmPREvaluators},
  UfrmMMBond in 'UfrmMMBond.pas' {frmMMBond},
  UfrmMMBondAllocationOrderPlacement in 'UfrmMMBondAllocationOrderPlacement.pas' {frmMMBondAllocationOrderPlacement},
  UfrmMMBondCoupon in 'UfrmMMBondCoupon.pas' {frmMMBondCoupon},
  UfrmMMBondDeal2AllocationOrder in 'UfrmMMBondDeal2AllocationOrder.pas' {frmMMBondDeal2AllocationOrder},
  UfrmMMBondDealList in 'UfrmMMBondDealList.pas' {frmMMBondDealList},
  UfrmMMBondDealSettlement in 'UfrmMMBondDealSettlement.pas' {frmMMBondDealSettlement},
  UfrmMMBondList in 'UfrmMMBondList.pas' {frmMMBondList},
  UfrmMMBondRates in 'UfrmMMBondRates.pas' {frmMMBondRates},
  UfrmMMBondScripDischarge in 'UfrmMMBondScripDischarge.pas' {frmMMBondScripDischarge},
  UfrmMMBondScripList in 'UfrmMMBondScripList.pas' {frmMMBondScripList},
  UfrmMMBondScripRegistration in 'UfrmMMBondScripRegistration.pas' {frmMMBondScripRegistration},
  UfrmMMBondScripTransfer in 'UfrmMMBondScripTransfer.pas' {frmMMBondScripTransfer},
  UfrmMMClientPortfolio in 'UfrmMMClientPortfolio.pas' {frmMMClientPortfolio},
  UfrmMMDealRates in 'UfrmMMDealRates.pas' {frmMMDealRates},
  UfrmMMLegend in 'UfrmMMLegend.pas' {frmMMLegend},
  UfrmMMBondCouponRedeem in 'UfrmMMBondCouponRedeem.pas' {frmMMBondCouponRedeem},
  UfrmUTUnitTrustConsolidation in 'UfrmUTUnitTrustConsolidation.pas' {frmUTUnitTrustConsolidation},
  UfrmCreateUnitConsolidation in 'UfrmCreateUnitConsolidation.pas' {frmCreateUnitConsolidation},
  UfrmUTLedgerFees in 'UfrmUTLedgerFees.pas' {frmUTLedgerFees},
  UfrmUTLedgerFeesCreate in 'UfrmUTLedgerFeesCreate.pas' {frmUTLedgerFeesCreate},
  UfrmUTDistributionCreate in 'UfrmUTDistributionCreate.pas' {frmUTDistributionCreate},
  UfrmMMAccountInterestList in 'UfrmMMAccountInterestList.pas' {frmMMAccountInterestList},
  Validation in 'Validation.pas',
  UfrmMMAllocationAuthorisation in 'UfrmMMAllocationAuthorisation.pas' {frmMMAllocationAuthorisation},
  UfrmMMPlacementAuthorisation in 'UfrmMMPlacementAuthorisation.pas' {frmMMPlacementAuthorisation},
  UfrmMMDealerAuthorisation in 'UfrmMMDealerAuthorisation.pas' {frmMMDealerAuthorisation},
  UfrmEQScripManualDischargeListing in 'UfrmEQScripManualDischargeListing.pas' {frmEQScripManualDischargeListing},
  UfrmImportSearch in 'UfrmImportSearch.pas' {frmImportSearch},
  UPRExpense in 'UPRExpense.pas' {frmPRPropertyExpense},
  UPRNewPropertyDeal in 'UPRNewPropertyDeal.pas' {frmPRPropertyDeal},
  UPRPropertyDetails in 'UPRPropertyDetails.pas' {frmPRProperty},
  UPRPropertyPurchaseDeal in 'UPRPropertyPurchaseDeal.pas' {frmPRPropertyPurchaseDeal},
  UPRUnitIssue in 'UPRUnitIssue.pas' {frmPRCreateUnitIssue},
  UPRLeaseCreate in 'UPRLeaseCreate.pas' {frmPRLeaseCreate},
  UfrmEQBatchAllocate in 'UfrmEQBatchAllocate.pas' {frmEQBatchAllocate},
  UfrmEQBatchSettle in 'UfrmEQBatchSettle.pas' {frmEQBatchSettle},
  UfrmMMBackDatedTransactions in 'UfrmMMBackDatedTransactions.pas' {frmMMBackDatedTransactions},
  UfrmMMCashForecast in 'UfrmMMCashForecast.pas' {frmMMCashForecast},
  UPRTenant in 'UPRTenant.pas' {frmPRTenant},
  UfrmEQOtherAssetCreate in 'UfrmEQOtherAssetCreate.pas' {frmEQOtherAssetCreate},
  UfrmTargetAnalysis in 'UfrmTargetAnalysis.pas' {frmTargetAnalysis},
  UfrmTargetAnalysisSetup in 'UfrmTargetAnalysisSetup.pas' {frmTargetAnalysisSetup},
  UfrmFundsUnderMgt in 'UfrmFundsUnderMgt.pas' {frmFundsUnderMgt},
  UfrmSafeCustody in 'UfrmSafeCustody.pas' {frmSafeCustody},
  UManagementFeeScheduleCreate in 'UManagementFeeScheduleCreate.pas' {frmManagementFeeScheduleCreate},
  UManagementFeeScheduleListing in 'UManagementFeeScheduleListing.pas' {frmManagementFeeScheduleList},
  UManagementFeeAllocationCreate in 'UManagementFeeAllocationCreate.pas' {frmManagementFeeAllocationCreate},
  UAssetManager in 'UAssetManager.pas' {frmAssetManager},
  UfrmAuthoriseOverdraw in 'UfrmAuthoriseOverdraw.pas' {frmAuthoriseOverdraw},
  UfrmTMONDeals in 'UfrmTMONDeals.pas' {frmTMONDeals},
  UfrmEmailDateSend in 'UfrmEmailDateSend.pas' {frmEmailDateSend},
  UfrmReleaseUserList in 'UfrmReleaseUserList.pas' {frmReleaseUser},
  UfrmDebenture in 'UfrmDebenture.pas' {frmDebenture},
  UfrmDebentureList in 'UfrmDebentureList.pas' {frmDebentureList},
  UfrmDebentureCoupon in 'UfrmDebentureCoupon.pas' {frmDebentureCoupon},
  UfrmDebentureAllocationOrderList in 'UfrmDebentureAllocationOrderList.pas' {frmDebentureAllocationOrderList},
  UfrmDebentureAllocationOrder in 'UfrmDebentureAllocationOrder.pas' {frmDebentureAllocationOrder},
  UfrmDebentureAllocationOrderItem in 'UfrmDebentureAllocationOrderItem.pas' {frmDebentureAllocationOrderItem},
  UfrmDebentureCouponRedeem in 'UfrmDebentureCouponRedeem.pas' {frmDebentureCouponRedeem},
  UfrmDebentureDealSettlement in 'UfrmDebentureDealSettlement.pas' {frmDebentureDealSettlement},
  UfrmDebentureDealList2 in 'UfrmDebentureDealList2.pas' {frmDebentureDealList2},
  UfrmDebentureDeal2AllocationOrder in 'UfrmDebentureDeal2AllocationOrder.pas' {frmDebentureDeal2AllocationOrder},
  UfrmUploadClients in 'UfrmUploadClients.pas' {frmUpLoadClients};

{$R *.res}

begin
  Application.Initialize;
  Application.Title := 'GS Custodial';
  Application.CreateForm(TfrmMain, frmMain);
  Application.CreateForm(TdtmMain, dtmMain);
  Application.CreateForm(TfrmManagementFeeScheduleCreate, frmManagementFeeScheduleCreate);
  Application.CreateForm(TfrmManagementFeeAllocationCreate, frmManagementFeeAllocationCreate);
  Application.CreateForm(TfrmAuthoriseOverdraw, frmAuthoriseOverdraw);
  Application.CreateForm(TfrmEmailDateSend, frmEmailDateSend);
  Application.Run;
end.
